### ISSUE TITLE
ImportError: dynamic module does not define init function (init_caffe)

### ISSUE THREAD

**Issue by yogayudistira** [nefrock/docker-ai-base-gpu#1]
When trying to `import caffe` errorr appear
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/opt/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define init function (init_caffe)
```

Excuted the container with `sudo nvidia-docker run -it nefrock/docker-ai-base-gpu`

**Comment by turuturu** [comment]
Thank you for raising the issue.
I upgrade the module, so may I build it again?
If it still seems to fail, please tell me your environment.
